const PUSH_NEW_PROJECT_REQUEST = "PUSH_NEW_PROJECT_REQUEST";
const PUSH_NEW_PROJECT_SUCEESS = "PUSH_NEW_PROJECT_SUCEESS";
const PUSH_NEW_PROJECT_FAIL = "PUSH_NEW_PROJECT_FAIL";
const PUSH_NEW_PROJECT_RESET = "PUSH_NEW_PROJECT_RESET";

const SINGLE_PRODUCT_REQUEST = "SINGLE_PRODUCT_REQUEST";
const SINGLE_PRODUCT_SUCEESS = "SINGLE_PRODUCT_SUCEESS";
const SINGLE_PRODUCT_FAIL = "SINGLE_PRODUCT_FAIL";


const GET_ALL_PROJECT__REQUEST = "GET_ALL_PROJECT__REQUEST";
const GET_ALL_PROJECT__SUCEESS = "GET_ALL_PROJECT__SUCEESS";
const GET_ALL_PROJECT__FAIL = "GET_ALL_PROJECT__FAIL";


const GET_ALL_PROJECT_USER_REQUEST = "GET_ALL_PROJECT_USER_REQUEST";
const GET_ALL_PROJECT_USER_SUCEESS = "GET_ALL_PROJECT_USER_SUCEESS";
const GET_ALL_PROJECT_USER_FAIL = "GET_ALL_PROJECT_USER_FAIL";


const LIKE_DISLIKE_PROJECT = 'LIKE_DISLIKE_PROJECT';
const LIKE_DISLIKE_FAILURE = 'LIKE_DISLIKE_FAILURE';



const INCREMENT_VIEWS_REQUEST = 'INCREMENT_VIEWS_REQUEST';
const INCREMENT_VIEWS_SUCCESS = 'INCREMENT_VIEWS_SUCCESS';
const INCREMENT_VIEWS_FAILURE = 'INCREMENT_VIEWS_FAILURE';




const UPDATE_PROJECT_DETIALS_REQUEST = "UPDATE_PROJECT_DETIALS_REQUEST";
const UPDATE_PROJECT_DETIALS_SUCEESS = "UPDATE_PROJECT_DETIALS_SUCEESS";
const UPDATE_PROJECT_DETIALS_FAIL = "UPDATE_PROJECT_DETIALS_FAIL";
const UPDATE_PROJECT_DETIALS_RESET = "UPDATE_PROJECT_DETIALS_RESET";



const DELETE_PROJECT_REQUEST = "DELETE_PROJECT_REQUEST";
const DELETE_PROJECT_SUCEESS = "DELETE_PROJECT_SUCEESS";
const DELETE_PROJECT_FAIL = "DELETE_PROJECT_FAIL";
const DELETE_PROJECT_RESET = "DELETE_PROJECT_RESET";

const DISLIKE_ITEM="DISLIKE_ITEM"


const CLEAR_ERRORS = "CLEAR_ERRORS";

export {
    PUSH_NEW_PROJECT_REQUEST,
    PUSH_NEW_PROJECT_SUCEESS,
    PUSH_NEW_PROJECT_FAIL,
    PUSH_NEW_PROJECT_RESET,
    SINGLE_PRODUCT_REQUEST,
    SINGLE_PRODUCT_SUCEESS,
    SINGLE_PRODUCT_FAIL,
    GET_ALL_PROJECT__REQUEST,
    GET_ALL_PROJECT__SUCEESS,
    GET_ALL_PROJECT__FAIL,
    GET_ALL_PROJECT_USER_REQUEST,
    GET_ALL_PROJECT_USER_SUCEESS,
    GET_ALL_PROJECT_USER_FAIL,
    LIKE_DISLIKE_PROJECT,
    LIKE_DISLIKE_FAILURE,
    INCREMENT_VIEWS_REQUEST,
    INCREMENT_VIEWS_SUCCESS,
    INCREMENT_VIEWS_FAILURE,
    UPDATE_PROJECT_DETIALS_REQUEST,
    UPDATE_PROJECT_DETIALS_SUCEESS,
    UPDATE_PROJECT_DETIALS_FAIL,
    UPDATE_PROJECT_DETIALS_RESET,
    DELETE_PROJECT_REQUEST,
    DELETE_PROJECT_SUCEESS,
    DELETE_PROJECT_FAIL,
    DELETE_PROJECT_RESET,
    DISLIKE_ITEM,
    CLEAR_ERRORS,
}



